### PR TITLE
Correctly type check boolean values

### LINKED ISSUE #133: Boolean values cannot be updated by specifying a "real" boolean value
Description:
Sensor and actuator values having the type "boolean" cannot be updated using "real" boolean values (true, false)

Environment:
- Error occurs on image build #55 (https://ci.eclipse.org/kuksa/job/kuksa.val/job/master/55/)

Steps to reproduce:
- Try to publish a sensor value of type "boolean" by transferring "real" booleans like true or false as value
  - An error response is sent back from Kuksa.VAL: "string or number is expected, received bool"
- If 0 or 1 is used, the sensor value can be successfully updated

Expected behavior:
- true and false are accepted, numbers and strings are rejected

### PR DESCRIPTION
**Pull request by SebastianSchildt**
Should fix #133 

```json
Test Client> setValue Vehicle.OBD.DriveCycleStatus.MIL foo
{
    "action": "set", 
    "error": {
        "message": "foo is not a bool. Valid values are true and false ", 
        "number": 400, 
        "reason": "Value passed is out of bounds"
    }, 
    "requestId": "9dfe6e60-3374-493a-aca8-30736a82d6f3", 
    "timestamp": 1616169129422
}

Test Client> setValue Vehicle.OBD.DriveCycleStatus.MIL true
{
    "action": "set", 
    "requestId": "a10e1ee1-9732-4704-ad28-e9c614d00501", 
    "timestamp": 1616169134986
}

Test Client> getValue Vehicle.OBD.DriveCycleStatus.MIL 
{
    "action": "get", 
    "path": "Vehicle.OBD.DriveCycleStatus.MIL", 
    "requestId": "2d6d790f-8c48-40fb-bb30-a22f2da76e01", 
    "timestamp": 1616169138448, 
    "value": true
}

Test Client> 
```

I guess the whole typeCheck code is due for a refactoring when we tacke #46

### CODE REVIEW

File: src/VssDatabase.cpp [hunk 1]
```diff
@@ -203,6 +202,22 @@ jsoncons::json tryParse(jsoncons::json val) {
         throw outOfBoundException(msg.str());
       }
     } else if (value_type == "boolean") {
+      string v=val.as<string>();
+      boost::algorithm::erase_all(v, "\"");
+
+      if ( v == "true") {
```
Comment (wenwenchenbosch) [inline src/VssDatabase.cpp:208]: would we like to also support "True", "TRUE"?

File: src/VssDatabase.cpp [hunk 2]
```diff
@@ -65,7 +65,7 @@ jsoncons::json tryParse(jsoncons::json val) {
 }
 
     // Check the value type and if the value is within the range
-  void checkTypeAndBound(std::shared_ptr<ILogger> logger, string value_type, jsoncons::json val) {
+  void checkTypeAndBound(std::shared_ptr<ILogger> logger, string value_type, jsoncons::json &val) {
```
Comment (wenwenchenbosch) [inline src/VssDatabase.cpp:68]:
```suggestion
  void checkTypeAndBound(std::shared_ptr<ILogger> logger, const string& value_type, const jsoncons::json &val) {
```

File: src/VssDatabase.cpp (hunk 1 above)
Comment (SebastianSchildt) [reply src/VssDatabase.cpp:208]: I checked and according to https://www.w3schools.com/js/js_json_datatypes.asp   only "true" and "false" in JSON, so I elft it at that. (and made the error message explicitly mentioning that)

**Review by wenwenchenbosch — APPROVED** [review]
